version: "3.9"
services:
  basic-crud-gui:
    build: ./basic-crud-gui
    environment:
      NODE_ENV: production
    depends_on:
      - db-broker
    ports:
      - "80:80"

  db-broker:
    build: ./db-broker
    command: npm start
    environment:
      NODE_ENV: production
    depends_on:
      - mongodb
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:4
    command: mongod
    ports:
      - "27017:27017"
